// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheHybridWatchStore.Server.Models;

#nullable disable

namespace TheHybridWatchStore.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240814145414_moreData")]
    partial class moreData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TheHybridWatchStore.Server.Data.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TheHybridWatchStore.Server.Data.Models.Watch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Features")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Movement")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Watches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Tissot",
                            Description = "A classic watch with a modern touch.",
                            Features = "[\"23 Jewels\",\"Date Display\",\"Water Resistant\"]",
                            Gender = "Unisex",
                            Movement = "Automatic",
                            Name = "Tissot T-Classic",
                            Price = 899.99m
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Rolex",
                            Description = "The Rolex Submariner is an iconic timepiece.",
                            Features = "[\"Water Resistant\",\"Chronometer\",\"Cerachrom Bezel\"]",
                            Gender = "Men",
                            Movement = "Automatic",
                            Name = "Rolex Submariner",
                            Price = 12500.00m
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Omega",
                            Description = "The first watch worn on the moon.",
                            Features = "[\"Chronograph\",\"Tachymeter\",\"Hesalite Crystal\"]",
                            Gender = "Men",
                            Movement = "Manual",
                            Name = "Omega Speedmaster",
                            Price = 5200.00m
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Tag Heuer",
                            Description = "A racing-inspired watch with a contemporary design.",
                            Features = "[\"Chronograph\",\"Sapphire Crystal\",\"Water Resistant\"]",
                            Gender = "Men",
                            Movement = "Automatic",
                            Name = "Tag Heuer Carrera",
                            Price = 4500.00m
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Cartier",
                            Description = "An elegant and timeless piece.",
                            Features = "[\"Sapphire Crystal\",\"Water Resistant\",\"Diamond Bezel\"]",
                            Gender = "Women",
                            Movement = "Quartz",
                            Name = "Cartier Tank",
                            Price = 3100.00m
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Breitling",
                            Description = "A classic aviation-inspired timepiece.",
                            Features = "[\"Chronograph\",\"Slide Rule Bezel\",\"Water Resistant\"]",
                            Gender = "Men",
                            Movement = "Automatic",
                            Name = "Breitling Navitimer",
                            Price = 7000.00m
                        },
                        new
                        {
                            Id = 7,
                            Brand = "IWC",
                            Description = "A sophisticated dress watch with a modern design.",
                            Features = "[\"Chronograph\",\"Sapphire Crystal\",\"Water Resistant\"]",
                            Gender = "Men",
                            Movement = "Automatic",
                            Name = "IWC Portugieser",
                            Price = 12500.00m
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Panerai",
                            Description = "A bold and rugged timepiece with Italian flair.",
                            Features = "[\"Power Reserve Indicator\",\"Date Display\",\"Water Resistant\"]",
                            Gender = "Men",
                            Movement = "Automatic",
                            Name = "Panerai Luminor",
                            Price = 8500.00m
                        },
                        new
                        {
                            Id = 9,
                            Brand = "Jaeger-LeCoultre",
                            Description = "An iconic watch with a reversible case.",
                            Features = "[\"Sapphire Crystal\",\"Water Resistant\",\"Reversible Case\"]",
                            Gender = "Men",
                            Movement = "Manual",
                            Name = "Jaeger-LeCoultre Reverso",
                            Price = 10000.00m
                        },
                        new
                        {
                            Id = 10,
                            Brand = "Audemars Piguet",
                            Description = "A luxury sports watch with an iconic design.",
                            Features = "[\"Sapphire Crystal\",\"Chronograph\",\"Water Resistant\"]",
                            Gender = "Men",
                            Movement = "Automatic",
                            Name = "Audemars Piguet Royal Oak",
                            Price = 22000.00m
                        },
                        new
                        {
                            Id = 11,
                            Brand = "Chanel",
                            Description = "A stylish and modern ceramic watch.",
                            Features = "[\"Ceramic Case\",\"Sapphire Crystal\",\"Water Resistant\"]",
                            Gender = "Women",
                            Movement = "Automatic",
                            Name = "Chanel J12",
                            Price = 5000.00m
                        },
                        new
                        {
                            Id = 12,
                            Brand = "Bulgari",
                            Description = "An elegant and distinctive watch with a snake motif.",
                            Features = "[\"Diamond Bezel\",\"Sapphire Crystal\",\"Water Resistant\"]",
                            Gender = "Women",
                            Movement = "Quartz",
                            Name = "Bulgari Serpenti",
                            Price = 8000.00m
                        },
                        new
                        {
                            Id = 13,
                            Brand = "Rolex",
                            Description = "A timeless and elegant watch for women.",
                            Features = "[\"Date Display\",\"Sapphire Crystal\",\"Water Resistant\"]",
                            Gender = "Women",
                            Movement = "Automatic",
                            Name = "Rolex Lady-Datejust",
                            Price = 9000.00m
                        },
                        new
                        {
                            Id = 14,
                            Brand = "Omega",
                            Description = "A luxurious and refined timepiece.",
                            Features = "[\"Diamond Bezel\",\"Sapphire Crystal\",\"Water Resistant\"]",
                            Gender = "Women",
                            Movement = "Automatic",
                            Name = "Omega Constellation",
                            Price = 7500.00m
                        },
                        new
                        {
                            Id = 15,
                            Brand = "Cartier",
                            Description = "A graceful and iconic watch with a unique shape.",
                            Features = "[\"Sapphire Crystal\",\"Water Resistant\",\"Diamond Markers\"]",
                            Gender = "Women",
                            Movement = "Automatic",
                            Name = "Cartier Ballon Bleu",
                            Price = 6000.00m
                        },
                        new
                        {
                            Id = 16,
                            Brand = "Apple",
                            Description = "The latest Apple Watch with advanced health features.",
                            Features = "[\"Heart Rate Monitor\",\"GPS\",\"Water Resistant\"]",
                            Gender = "Unisex",
                            Movement = "Smart",
                            Name = "Apple Watch Series 7",
                            Price = 399.99m
                        },
                        new
                        {
                            Id = 17,
                            Brand = "Samsung",
                            Description = "A powerful smartwatch with fitness tracking.",
                            Features = "[\"Sleep Tracking\",\"GPS\",\"Water Resistant\"]",
                            Gender = "Unisex",
                            Movement = "Smart",
                            Name = "Samsung Galaxy Watch 5",
                            Price = 349.99m
                        },
                        new
                        {
                            Id = 18,
                            Brand = "Garmin",
                            Description = "A rugged smartwatch for outdoor adventures.",
                            Features = "[\"GPS\",\"Pulse Ox Sensor\",\"Water Resistant\"]",
                            Gender = "Unisex",
                            Movement = "Smart",
                            Name = "Garmin Fenix 6",
                            Price = 599.99m
                        },
                        new
                        {
                            Id = 19,
                            Brand = "Fitbit",
                            Description = "A smartwatch with advanced health and fitness features.",
                            Features = "[\"Heart Rate Monitor\",\"ECG App\",\"Water Resistant\"]",
                            Gender = "Unisex",
                            Movement = "Smart",
                            Name = "Fitbit Sense",
                            Price = 329.99m
                        },
                        new
                        {
                            Id = 20,
                            Brand = "Fossil",
                            Description = "A stylish smartwatch with Wear OS.",
                            Features = "[\"Google Assistant\",\"GPS\",\"Water Resistant\"]",
                            Gender = "Unisex",
                            Movement = "Smart",
                            Name = "Fossil Gen 6",
                            Price = 299.99m
                        });
                });

            modelBuilder.Entity("TheHybridWatchStore.Server.Data.Models.WatchImage", b =>
                {
                    b.Property<int>("ImagesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImagesId"));

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WatchId")
                        .HasColumnType("int");

                    b.HasKey("ImagesId");

                    b.HasIndex("WatchId");

                    b.ToTable("WatchImages");

                    b.HasData(
                        new
                        {
                            ImagesId = 1,
                            ImagePath = "assets/imgs/watches/1-1.jpg",
                            WatchId = 1
                        },
                        new
                        {
                            ImagesId = 2,
                            ImagePath = "assets/imgs/watches/1-2.jpg",
                            WatchId = 1
                        },
                        new
                        {
                            ImagesId = 3,
                            ImagePath = "assets/imgs/watches/2-1.jpg",
                            WatchId = 2
                        },
                        new
                        {
                            ImagesId = 4,
                            ImagePath = "assets/imgs/watches/2-2.jpg",
                            WatchId = 2
                        },
                        new
                        {
                            ImagesId = 5,
                            ImagePath = "assets/imgs/watches/3-1.jpg",
                            WatchId = 3
                        },
                        new
                        {
                            ImagesId = 6,
                            ImagePath = "assets/imgs/watches/3-2.jpg",
                            WatchId = 3
                        },
                        new
                        {
                            ImagesId = 7,
                            ImagePath = "assets/imgs/watches/4-1.jpg",
                            WatchId = 4
                        },
                        new
                        {
                            ImagesId = 8,
                            ImagePath = "assets/imgs/watches/4-2.jpg",
                            WatchId = 4
                        },
                        new
                        {
                            ImagesId = 9,
                            ImagePath = "assets/imgs/watches/5-1.jpg",
                            WatchId = 5
                        },
                        new
                        {
                            ImagesId = 10,
                            ImagePath = "assets/imgs/watches/5-2.jpg",
                            WatchId = 5
                        },
                        new
                        {
                            ImagesId = 11,
                            ImagePath = "assets/imgs/watches/6-1.jpg",
                            WatchId = 6
                        },
                        new
                        {
                            ImagesId = 12,
                            ImagePath = "assets/imgs/watches/6-2.jpg",
                            WatchId = 6
                        },
                        new
                        {
                            ImagesId = 13,
                            ImagePath = "assets/imgs/watches/7-1.jpg",
                            WatchId = 7
                        },
                        new
                        {
                            ImagesId = 14,
                            ImagePath = "assets/imgs/watches/7-2.jpg",
                            WatchId = 7
                        },
                        new
                        {
                            ImagesId = 15,
                            ImagePath = "assets/imgs/watches/8-1.jpg",
                            WatchId = 8
                        },
                        new
                        {
                            ImagesId = 16,
                            ImagePath = "assets/imgs/watches/8-2.jpg",
                            WatchId = 8
                        },
                        new
                        {
                            ImagesId = 17,
                            ImagePath = "assets/imgs/watches/9-1.jpg",
                            WatchId = 9
                        },
                        new
                        {
                            ImagesId = 18,
                            ImagePath = "assets/imgs/watches/9-2.jpg",
                            WatchId = 9
                        },
                        new
                        {
                            ImagesId = 19,
                            ImagePath = "assets/imgs/watches/10-1.jpg",
                            WatchId = 10
                        },
                        new
                        {
                            ImagesId = 20,
                            ImagePath = "assets/imgs/watches/10-2.jpg",
                            WatchId = 10
                        },
                        new
                        {
                            ImagesId = 21,
                            ImagePath = "assets/imgs/watches/11-1.jpg",
                            WatchId = 11
                        },
                        new
                        {
                            ImagesId = 22,
                            ImagePath = "assets/imgs/watches/11-2.jpg",
                            WatchId = 11
                        },
                        new
                        {
                            ImagesId = 23,
                            ImagePath = "assets/imgs/watches/12-1.jpg",
                            WatchId = 12
                        },
                        new
                        {
                            ImagesId = 24,
                            ImagePath = "assets/imgs/watches/12-2.jpg",
                            WatchId = 12
                        },
                        new
                        {
                            ImagesId = 25,
                            ImagePath = "assets/imgs/watches/13-1.jpg",
                            WatchId = 13
                        },
                        new
                        {
                            ImagesId = 26,
                            ImagePath = "assets/imgs/watches/13-2.jpg",
                            WatchId = 13
                        },
                        new
                        {
                            ImagesId = 27,
                            ImagePath = "assets/imgs/watches/14-1.jpg",
                            WatchId = 14
                        },
                        new
                        {
                            ImagesId = 28,
                            ImagePath = "assets/imgs/watches/14-2.jpg",
                            WatchId = 14
                        },
                        new
                        {
                            ImagesId = 29,
                            ImagePath = "assets/imgs/watches/15-1.jpg",
                            WatchId = 15
                        },
                        new
                        {
                            ImagesId = 30,
                            ImagePath = "assets/imgs/watches/15-2.jpg",
                            WatchId = 15
                        },
                        new
                        {
                            ImagesId = 31,
                            ImagePath = "assets/imgs/watches/16-1.jpg",
                            WatchId = 16
                        },
                        new
                        {
                            ImagesId = 32,
                            ImagePath = "assets/imgs/watches/16-2.jpg",
                            WatchId = 16
                        },
                        new
                        {
                            ImagesId = 33,
                            ImagePath = "assets/imgs/watches/17-1.jpg",
                            WatchId = 17
                        },
                        new
                        {
                            ImagesId = 34,
                            ImagePath = "assets/imgs/watches/17-2.jpg",
                            WatchId = 17
                        },
                        new
                        {
                            ImagesId = 35,
                            ImagePath = "assets/imgs/watches/18-1.jpg",
                            WatchId = 18
                        },
                        new
                        {
                            ImagesId = 36,
                            ImagePath = "assets/imgs/watches/18-2.jpg",
                            WatchId = 18
                        },
                        new
                        {
                            ImagesId = 37,
                            ImagePath = "assets/imgs/watches/19-1.jpg",
                            WatchId = 19
                        },
                        new
                        {
                            ImagesId = 38,
                            ImagePath = "assets/imgs/watches/19-2.jpg",
                            WatchId = 19
                        },
                        new
                        {
                            ImagesId = 39,
                            ImagePath = "assets/imgs/watches/20-1.jpg",
                            WatchId = 20
                        },
                        new
                        {
                            ImagesId = 40,
                            ImagePath = "assets/imgs/watches/20-1.jpg",
                            WatchId = 20
                        });
                });

            modelBuilder.Entity("TheHybridWatchStore.Server.Data.Models.WatchSpecs", b =>
                {
                    b.Property<int>("SpecsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SpecsId"));

                    b.Property<double>("CaseDiameter")
                        .HasColumnType("float");

                    b.Property<string>("CaseMaterial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CaseShape")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("CaseThickness")
                        .HasColumnType("float");

                    b.Property<string>("DialColor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Engine")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PowerReserve")
                        .HasColumnType("int");

                    b.Property<string>("StrapMaterial")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("WatchId")
                        .HasColumnType("int");

                    b.Property<int>("WaterResistanceDepth")
                        .HasColumnType("int");

                    b.HasKey("SpecsId");

                    b.HasIndex("WatchId")
                        .IsUnique();

                    b.ToTable("WatchSpecs");

                    b.HasData(
                        new
                        {
                            SpecsId = 1,
                            CaseDiameter = 40.0,
                            CaseMaterial = "Stainless Steel",
                            CaseShape = "Round",
                            CaseThickness = 10.0,
                            DialColor = "Blue",
                            Engine = "Caliber: ETA C07.111",
                            PowerReserve = 80,
                            StrapMaterial = "Leather",
                            WatchId = 1,
                            WaterResistanceDepth = 50
                        },
                        new
                        {
                            SpecsId = 2,
                            CaseDiameter = 41.0,
                            CaseMaterial = "Stainless Steel",
                            CaseShape = "Round",
                            CaseThickness = 12.5,
                            DialColor = "Black",
                            Engine = "Caliber 3230",
                            PowerReserve = 70,
                            StrapMaterial = "Oyster Steel",
                            WatchId = 2,
                            WaterResistanceDepth = 300
                        },
                        new
                        {
                            SpecsId = 3,
                            CaseDiameter = 42.0,
                            CaseMaterial = "Stainless Steel",
                            CaseShape = "Round",
                            CaseThickness = 14.300000000000001,
                            DialColor = "Black",
                            Engine = "Caliber 1861",
                            PowerReserve = 48,
                            StrapMaterial = "Stainless Steel",
                            WatchId = 3,
                            WaterResistanceDepth = 50
                        },
                        new
                        {
                            SpecsId = 4,
                            CaseDiameter = 43.0,
                            CaseMaterial = "Stainless Steel",
                            CaseShape = "Round",
                            CaseThickness = 15.0,
                            DialColor = "Black",
                            Engine = "Caliber Heuer 02",
                            PowerReserve = 80,
                            StrapMaterial = "Leather",
                            WatchId = 4,
                            WaterResistanceDepth = 100
                        },
                        new
                        {
                            SpecsId = 5,
                            CaseDiameter = 29.5,
                            CaseMaterial = "18K Yellow Gold",
                            CaseShape = "Square",
                            CaseThickness = 6.5999999999999996,
                            DialColor = "White",
                            Engine = "Caliber 076",
                            PowerReserve = 36,
                            StrapMaterial = "Leather",
                            WatchId = 5,
                            WaterResistanceDepth = 30
                        },
                        new
                        {
                            SpecsId = 6,
                            CaseDiameter = 43.0,
                            CaseMaterial = "Stainless Steel",
                            CaseShape = "Round",
                            CaseThickness = 14.5,
                            DialColor = "Black",
                            Engine = "Caliber Breitling 01",
                            PowerReserve = 70,
                            StrapMaterial = "Leather",
                            WatchId = 6,
                            WaterResistanceDepth = 30
                        },
                        new
                        {
                            SpecsId = 7,
                            CaseDiameter = 41.0,
                            CaseMaterial = "18K Rose Gold",
                            CaseShape = "Round",
                            CaseThickness = 12.300000000000001,
                            DialColor = "Silver",
                            Engine = "Caliber 69355",
                            PowerReserve = 46,
                            StrapMaterial = "Leather",
                            WatchId = 7,
                            WaterResistanceDepth = 30
                        },
                        new
                        {
                            SpecsId = 8,
                            CaseDiameter = 44.0,
                            CaseMaterial = "Titanium",
                            CaseShape = "Cushion",
                            CaseThickness = 15.6,
                            DialColor = "Black",
                            Engine = "Caliber P.9010",
                            PowerReserve = 72,
                            StrapMaterial = "Rubber",
                            WatchId = 8,
                            WaterResistanceDepth = 300
                        },
                        new
                        {
                            SpecsId = 9,
                            CaseDiameter = 28.800000000000001,
                            CaseMaterial = "Stainless Steel",
                            CaseShape = "Rectangle",
                            CaseThickness = 9.5,
                            DialColor = "Silver",
                            Engine = "Caliber 822",
                            PowerReserve = 45,
                            StrapMaterial = "Leather",
                            WatchId = 9,
                            WaterResistanceDepth = 30
                        },
                        new
                        {
                            SpecsId = 10,
                            CaseDiameter = 41.0,
                            CaseMaterial = "Stainless Steel",
                            CaseShape = "Octagonal",
                            CaseThickness = 10.4,
                            DialColor = "Blue",
                            Engine = "Caliber 2385",
                            PowerReserve = 40,
                            StrapMaterial = "Stainless Steel",
                            WatchId = 10,
                            WaterResistanceDepth = 50
                        },
                        new
                        {
                            SpecsId = 11,
                            CaseDiameter = 38.0,
                            CaseMaterial = "Ceramic",
                            CaseShape = "Round",
                            CaseThickness = 11.5,
                            DialColor = "White",
                            Engine = "Caliber 12.1",
                            PowerReserve = 70,
                            StrapMaterial = "Ceramic",
                            WatchId = 11,
                            WaterResistanceDepth = 200
                        },
                        new
                        {
                            SpecsId = 12,
                            CaseDiameter = 35.0,
                            CaseMaterial = "18K Rose Gold",
                            CaseShape = "Teardrop",
                            CaseThickness = 7.5,
                            DialColor = "Pink",
                            Engine = "Caliber B033",
                            PowerReserve = 42,
                            StrapMaterial = "Leather",
                            WatchId = 12,
                            WaterResistanceDepth = 30
                        },
                        new
                        {
                            SpecsId = 13,
                            CaseDiameter = 28.0,
                            CaseMaterial = "Stainless Steel",
                            CaseShape = "Round",
                            CaseThickness = 10.5,
                            DialColor = "Silver",
                            Engine = "Caliber 2235",
                            PowerReserve = 48,
                            StrapMaterial = "Oyster Steel",
                            WatchId = 13,
                            WaterResistanceDepth = 100
                        },
                        new
                        {
                            SpecsId = 14,
                            CaseDiameter = 32.0,
                            CaseMaterial = "Stainless Steel",
                            CaseShape = "Round",
                            CaseThickness = 10.5,
                            DialColor = "Mother of Pearl",
                            Engine = "Caliber 8800",
                            PowerReserve = 55,
                            StrapMaterial = "Leather",
                            WatchId = 14,
                            WaterResistanceDepth = 100
                        },
                        new
                        {
                            SpecsId = 15,
                            CaseDiameter = 36.600000000000001,
                            CaseMaterial = "Stainless Steel",
                            CaseShape = "Round",
                            CaseThickness = 12.1,
                            DialColor = "Silver",
                            Engine = "Caliber 076",
                            PowerReserve = 36,
                            StrapMaterial = "Leather",
                            WatchId = 15,
                            WaterResistanceDepth = 30
                        },
                        new
                        {
                            SpecsId = 16,
                            CaseDiameter = 45.0,
                            CaseMaterial = "Aluminum",
                            CaseShape = "Rectangle",
                            CaseThickness = 10.699999999999999,
                            DialColor = "Black",
                            Engine = "Apple S7",
                            PowerReserve = 18,
                            StrapMaterial = "Fluoroelastomer",
                            WatchId = 16,
                            WaterResistanceDepth = 50
                        },
                        new
                        {
                            SpecsId = 17,
                            CaseDiameter = 44.0,
                            CaseMaterial = "Stainless Steel",
                            CaseShape = "Round",
                            CaseThickness = 11.1,
                            DialColor = "Silver",
                            Engine = "Exynos W920",
                            PowerReserve = 40,
                            StrapMaterial = "Leather",
                            WatchId = 17,
                            WaterResistanceDepth = 50
                        },
                        new
                        {
                            SpecsId = 18,
                            CaseDiameter = 47.0,
                            CaseMaterial = "Fiber-reinforced polymer",
                            CaseShape = "Round",
                            CaseThickness = 15.800000000000001,
                            DialColor = "Black",
                            Engine = "Garmin",
                            PowerReserve = 336,
                            StrapMaterial = "Silicone",
                            WatchId = 18,
                            WaterResistanceDepth = 100
                        },
                        new
                        {
                            SpecsId = 19,
                            CaseDiameter = 40.5,
                            CaseMaterial = "Stainless Steel",
                            CaseShape = "Square",
                            CaseThickness = 12.4,
                            DialColor = "Black",
                            Engine = "Fitbit OS",
                            PowerReserve = 72,
                            StrapMaterial = "Silicone",
                            WatchId = 19,
                            WaterResistanceDepth = 50
                        },
                        new
                        {
                            SpecsId = 20,
                            CaseDiameter = 44.0,
                            CaseMaterial = "Stainless Steel",
                            CaseShape = "Round",
                            CaseThickness = 12.5,
                            DialColor = "Black",
                            Engine = "Snapdragon Wear 4100+",
                            PowerReserve = 24,
                            StrapMaterial = "Leather",
                            WatchId = 20,
                            WaterResistanceDepth = 30
                        });
                });

            modelBuilder.Entity("TheHybridWatchStore.Server.Data.Models.WatchImage", b =>
                {
                    b.HasOne("TheHybridWatchStore.Server.Data.Models.Watch", "Watch")
                        .WithMany("Images")
                        .HasForeignKey("WatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Watch");
                });

            modelBuilder.Entity("TheHybridWatchStore.Server.Data.Models.WatchSpecs", b =>
                {
                    b.HasOne("TheHybridWatchStore.Server.Data.Models.Watch", "Watch")
                        .WithOne("Specs")
                        .HasForeignKey("TheHybridWatchStore.Server.Data.Models.WatchSpecs", "WatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Watch");
                });

            modelBuilder.Entity("TheHybridWatchStore.Server.Data.Models.Watch", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Specs")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
