// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheHybridWatchStore.Server.Models;

#nullable disable

namespace TheHybridWatchStore.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240812202027_navpropAdded")]
    partial class navpropAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TheHybridWatchStore.Server.Data.Models.Watch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Features")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Movement")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Watches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Tissot",
                            Description = "A classic watch with a modern touch.",
                            Features = "[\"23 Jewels\",\"Date Display\",\"Water Resistant\"]",
                            Gender = "Unisex",
                            Movement = "Automatic",
                            Name = "Tissot T-Classic",
                            Price = 899.99m
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Rolex",
                            Description = "The Rolex Submariner is an iconic timepiece.",
                            Features = "[\"Water Resistant\",\"Chronometer\",\"Cerachrom Bezel\"]",
                            Gender = "Men",
                            Movement = "Automatic",
                            Name = "Rolex Submariner",
                            Price = 12500.00m
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Omega",
                            Description = "The first watch worn on the moon.",
                            Features = "[\"Chronograph\",\"Tachymeter\",\"Hesalite Crystal\"]",
                            Gender = "Men",
                            Movement = "Manual",
                            Name = "Omega Speedmaster",
                            Price = 5200.00m
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Tag Heuer",
                            Description = "A racing-inspired watch with a contemporary design.",
                            Features = "[\"Chronograph\",\"Sapphire Crystal\",\"Water Resistant\"]",
                            Gender = "Men",
                            Movement = "Automatic",
                            Name = "Tag Heuer Carrera",
                            Price = 4500.00m
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Cartier",
                            Description = "An elegant and timeless piece.",
                            Features = "[\"Sapphire Crystal\",\"Water Resistant\",\"Diamond Bezel\"]",
                            Gender = "Women",
                            Movement = "Quartz",
                            Name = "Cartier Tank",
                            Price = 3100.00m
                        });
                });

            modelBuilder.Entity("TheHybridWatchStore.Server.Data.Models.WatchImage", b =>
                {
                    b.Property<int>("ImagesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImagesId"));

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WatchId")
                        .HasColumnType("int");

                    b.HasKey("ImagesId");

                    b.HasIndex("WatchId");

                    b.ToTable("WatchImages");

                    b.HasData(
                        new
                        {
                            ImagesId = 1,
                            ImagePath = "assets/imgs/watches/1-1.jpg",
                            WatchId = 1
                        },
                        new
                        {
                            ImagesId = 2,
                            ImagePath = "assets/imgs/watches/1-2.jpg",
                            WatchId = 1
                        },
                        new
                        {
                            ImagesId = 3,
                            ImagePath = "assets/imgs/watches/2-1.jpg",
                            WatchId = 2
                        },
                        new
                        {
                            ImagesId = 4,
                            ImagePath = "assets/imgs/watches/2-2.jpg",
                            WatchId = 2
                        },
                        new
                        {
                            ImagesId = 5,
                            ImagePath = "assets/imgs/watches/3-1.jpg",
                            WatchId = 3
                        },
                        new
                        {
                            ImagesId = 6,
                            ImagePath = "assets/imgs/watches/3-2.jpg",
                            WatchId = 3
                        },
                        new
                        {
                            ImagesId = 7,
                            ImagePath = "assets/imgs/watches/4-1.jpg",
                            WatchId = 4
                        },
                        new
                        {
                            ImagesId = 8,
                            ImagePath = "assets/imgs/watches/4-2.jpg",
                            WatchId = 4
                        },
                        new
                        {
                            ImagesId = 9,
                            ImagePath = "assets/imgs/watches/5-1.jpg",
                            WatchId = 5
                        },
                        new
                        {
                            ImagesId = 10,
                            ImagePath = "assets/imgs/watches/5-2.jpg",
                            WatchId = 5
                        });
                });

            modelBuilder.Entity("TheHybridWatchStore.Server.Data.Models.WatchSpecs", b =>
                {
                    b.Property<int>("SpecsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SpecsId"));

                    b.Property<double>("CaseDiameter")
                        .HasColumnType("float");

                    b.Property<string>("CaseMaterial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CaseShape")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("CaseThickness")
                        .HasColumnType("float");

                    b.Property<string>("DialColor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Engine")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PowerReserve")
                        .HasColumnType("int");

                    b.Property<string>("StrapMaterial")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("WatchId")
                        .HasColumnType("int");

                    b.Property<int>("WaterResistanceDepth")
                        .HasColumnType("int");

                    b.HasKey("SpecsId");

                    b.HasIndex("WatchId")
                        .IsUnique();

                    b.ToTable("WatchSpecs");

                    b.HasData(
                        new
                        {
                            SpecsId = 1,
                            CaseDiameter = 40.0,
                            CaseMaterial = "Stainless Steel",
                            CaseShape = "Round",
                            CaseThickness = 10.0,
                            DialColor = "Blue",
                            Engine = "Caliber: ETA C07.111",
                            PowerReserve = 80,
                            StrapMaterial = "Leather",
                            WatchId = 1,
                            WaterResistanceDepth = 50
                        },
                        new
                        {
                            SpecsId = 2,
                            CaseDiameter = 41.0,
                            CaseMaterial = "Stainless Steel",
                            CaseShape = "Round",
                            CaseThickness = 12.5,
                            DialColor = "Black",
                            Engine = "Caliber 3230",
                            PowerReserve = 70,
                            StrapMaterial = "Oyster Steel",
                            WatchId = 2,
                            WaterResistanceDepth = 300
                        },
                        new
                        {
                            SpecsId = 3,
                            CaseDiameter = 42.0,
                            CaseMaterial = "Stainless Steel",
                            CaseShape = "Round",
                            CaseThickness = 14.300000000000001,
                            DialColor = "Black",
                            Engine = "Caliber 1861",
                            PowerReserve = 48,
                            StrapMaterial = "Stainless Steel",
                            WatchId = 3,
                            WaterResistanceDepth = 50
                        },
                        new
                        {
                            SpecsId = 4,
                            CaseDiameter = 43.0,
                            CaseMaterial = "Stainless Steel",
                            CaseShape = "Round",
                            CaseThickness = 15.0,
                            DialColor = "Black",
                            Engine = "Caliber Heuer 02",
                            PowerReserve = 80,
                            StrapMaterial = "Leather",
                            WatchId = 4,
                            WaterResistanceDepth = 100
                        },
                        new
                        {
                            SpecsId = 5,
                            CaseDiameter = 29.5,
                            CaseMaterial = "18K Yellow Gold",
                            CaseShape = "Square",
                            CaseThickness = 6.5999999999999996,
                            DialColor = "White",
                            Engine = "Caliber 076",
                            PowerReserve = 36,
                            StrapMaterial = "Leather",
                            WatchId = 5,
                            WaterResistanceDepth = 30
                        });
                });

            modelBuilder.Entity("TheHybridWatchStore.Server.Data.Models.WatchImage", b =>
                {
                    b.HasOne("TheHybridWatchStore.Server.Data.Models.Watch", "Watch")
                        .WithMany("Images")
                        .HasForeignKey("WatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Watch");
                });

            modelBuilder.Entity("TheHybridWatchStore.Server.Data.Models.WatchSpecs", b =>
                {
                    b.HasOne("TheHybridWatchStore.Server.Data.Models.Watch", "Watch")
                        .WithOne("Specs")
                        .HasForeignKey("TheHybridWatchStore.Server.Data.Models.WatchSpecs", "WatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Watch");
                });

            modelBuilder.Entity("TheHybridWatchStore.Server.Data.Models.Watch", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Specs")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
